/**
 * @file tcs.c
 *
 * @brief This source file was generated by cantools version 40.2.1 Tue Feb 18 00:50:00 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "tcs.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int tcs_shift_controller_pack(
    uint8_t *dst_p,
    const struct tcs_shift_controller_t *src_p,
    size_t size)
{
    uint16_t clutch_left;
    uint16_t clutch_right;
    uint8_t down;
    uint8_t up;

    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    down = (uint8_t)src_p->down;
    dst_p[0] |= pack_left_shift_u8(down, 1u, 0x02u);
    up = (uint8_t)src_p->up;
    dst_p[0] |= pack_left_shift_u8(up, 0u, 0x01u);
    clutch_right = (uint16_t)src_p->clutch_right;
    dst_p[1] |= pack_right_shift_u16(clutch_right, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(clutch_right, 0u, 0xffu);
    clutch_left = (uint16_t)src_p->clutch_left;
    dst_p[3] |= pack_right_shift_u16(clutch_left, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(clutch_left, 0u, 0xffu);

    return (5);
}

int tcs_shift_controller_unpack(
    struct tcs_shift_controller_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t clutch_left;
    uint16_t clutch_right;
    uint8_t down;
    uint8_t up;

    if (size < 5u) {
        return (-EINVAL);
    }

    down = unpack_right_shift_u8(src_p[0], 1u, 0x02u);

    if ((down & (1u << 0)) != 0u) {
        down |= 0xfeu;
    }

    dst_p->down = (int8_t)down;
    up = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    if ((up & (1u << 0)) != 0u) {
        up |= 0xfeu;
    }

    dst_p->up = (int8_t)up;
    clutch_right = unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    clutch_right |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->clutch_right = (int16_t)clutch_right;
    clutch_left = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    clutch_left |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->clutch_left = (int16_t)clutch_left;

    return (0);
}

int tcs_shift_controller_init(struct tcs_shift_controller_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct tcs_shift_controller_t));

    return 0;
}

int8_t tcs_shift_controller_down_encode(double value)
{
    return (int8_t)(value);
}

double tcs_shift_controller_down_decode(int8_t value)
{
    return ((double)value);
}

bool tcs_shift_controller_down_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t tcs_shift_controller_up_encode(double value)
{
    return (int8_t)(value);
}

double tcs_shift_controller_up_decode(int8_t value)
{
    return ((double)value);
}

bool tcs_shift_controller_up_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int16_t tcs_shift_controller_clutch_right_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double tcs_shift_controller_clutch_right_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool tcs_shift_controller_clutch_right_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t tcs_shift_controller_clutch_left_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double tcs_shift_controller_clutch_left_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool tcs_shift_controller_clutch_left_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int tcs_clutch_pack(
    uint8_t *dst_p,
    const struct tcs_clutch_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_right_shift_u16(src_p->position, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->position, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->position_percentage, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->position_percentage, 0u, 0xffu);

    return (4);
}

int tcs_clutch_unpack(
    struct tcs_clutch_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->position = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->position |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->position_percentage = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->position_percentage |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);

    return (0);
}

int tcs_clutch_init(struct tcs_clutch_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct tcs_clutch_t));

    return 0;
}

uint16_t tcs_clutch_position_encode(double value)
{
    return (uint16_t)(value);
}

double tcs_clutch_position_decode(uint16_t value)
{
    return ((double)value);
}

bool tcs_clutch_position_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t tcs_clutch_position_percentage_encode(double value)
{
    return (uint16_t)(value);
}

double tcs_clutch_position_percentage_decode(uint16_t value)
{
    return ((double)value);
}

bool tcs_clutch_position_percentage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int tcs_set_clutch_pack(
    uint8_t *dst_p,
    const struct tcs_set_clutch_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_right_shift_u16(src_p->set_position, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->set_position, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->set_state, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->set_state, 0u, 0xffu);

    return (4);
}

int tcs_set_clutch_unpack(
    struct tcs_set_clutch_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->set_position = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->set_position |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->set_state = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->set_state |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);

    return (0);
}

int tcs_set_clutch_init(struct tcs_set_clutch_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct tcs_set_clutch_t));

    return 0;
}

uint16_t tcs_set_clutch_set_position_encode(double value)
{
    return (uint16_t)(value);
}

double tcs_set_clutch_set_position_decode(uint16_t value)
{
    return ((double)value);
}

bool tcs_set_clutch_set_position_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t tcs_set_clutch_set_state_encode(double value)
{
    return (uint16_t)(value);
}

double tcs_set_clutch_set_state_decode(uint16_t value)
{
    return ((double)value);
}

bool tcs_set_clutch_set_state_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int tcs_analog_input_pack(
    uint8_t *dst_p,
    const struct tcs_analog_input_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->input_right_travel, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->input_right_travel, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->input_right_raw, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->input_right_raw, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->input_left_travel, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->input_left_travel, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->input_left_raw, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->input_left_raw, 0u, 0xffu);

    return (8);
}

int tcs_analog_input_unpack(
    struct tcs_analog_input_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->input_right_travel = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->input_right_travel |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->input_right_raw = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->input_right_raw |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->input_left_travel = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->input_left_travel |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->input_left_raw = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->input_left_raw |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int tcs_analog_input_init(struct tcs_analog_input_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct tcs_analog_input_t));

    return 0;
}

uint16_t tcs_analog_input_input_right_travel_encode(double value)
{
    return (uint16_t)(value);
}

double tcs_analog_input_input_right_travel_decode(uint16_t value)
{
    return ((double)value);
}

bool tcs_analog_input_input_right_travel_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t tcs_analog_input_input_right_raw_encode(double value)
{
    return (uint16_t)(value);
}

double tcs_analog_input_input_right_raw_decode(uint16_t value)
{
    return ((double)value);
}

bool tcs_analog_input_input_right_raw_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t tcs_analog_input_input_left_travel_encode(double value)
{
    return (uint16_t)(value);
}

double tcs_analog_input_input_left_travel_decode(uint16_t value)
{
    return ((double)value);
}

bool tcs_analog_input_input_left_travel_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t tcs_analog_input_input_left_raw_encode(double value)
{
    return (uint16_t)(value);
}

double tcs_analog_input_input_left_raw_decode(uint16_t value)
{
    return ((double)value);
}

bool tcs_analog_input_input_left_raw_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int tcs_set_clutch_settings_pack(
    uint8_t *dst_p,
    const struct tcs_set_clutch_settings_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->set_start, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->set_start, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->set_end, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->set_end, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->set_friction, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->set_friction, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->set_auto_launch, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->set_auto_launch, 0u, 0xffu);

    return (8);
}

int tcs_set_clutch_settings_unpack(
    struct tcs_set_clutch_settings_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->set_start = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->set_start |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->set_end = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->set_end |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->set_friction = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->set_friction |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->set_auto_launch = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->set_auto_launch |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int tcs_set_clutch_settings_init(struct tcs_set_clutch_settings_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct tcs_set_clutch_settings_t));

    return 0;
}

uint16_t tcs_set_clutch_settings_set_start_encode(double value)
{
    return (uint16_t)(value);
}

double tcs_set_clutch_settings_set_start_decode(uint16_t value)
{
    return ((double)value);
}

bool tcs_set_clutch_settings_set_start_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t tcs_set_clutch_settings_set_end_encode(double value)
{
    return (uint16_t)(value);
}

double tcs_set_clutch_settings_set_end_decode(uint16_t value)
{
    return ((double)value);
}

bool tcs_set_clutch_settings_set_end_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t tcs_set_clutch_settings_set_friction_encode(double value)
{
    return (uint16_t)(value);
}

double tcs_set_clutch_settings_set_friction_decode(uint16_t value)
{
    return ((double)value);
}

bool tcs_set_clutch_settings_set_friction_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t tcs_set_clutch_settings_set_auto_launch_encode(double value)
{
    return (uint16_t)(value);
}

double tcs_set_clutch_settings_set_auto_launch_decode(uint16_t value)
{
    return ((double)value);
}

bool tcs_set_clutch_settings_set_auto_launch_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int tcs_set_shift_settings_pack(
    uint8_t *dst_p,
    const struct tcs_set_shift_settings_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->set_up_delay, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->set_up_delay, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->set_down_delay, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->set_down_delay, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->set_output, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->set_output, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->set_timeout, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->set_timeout, 0u, 0xffu);

    return (8);
}

int tcs_set_shift_settings_unpack(
    struct tcs_set_shift_settings_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->set_up_delay = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->set_up_delay |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->set_down_delay = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->set_down_delay |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->set_output = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->set_output |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->set_timeout = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->set_timeout |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int tcs_set_shift_settings_init(struct tcs_set_shift_settings_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct tcs_set_shift_settings_t));

    return 0;
}

uint16_t tcs_set_shift_settings_set_up_delay_encode(double value)
{
    return (uint16_t)(value);
}

double tcs_set_shift_settings_set_up_delay_decode(uint16_t value)
{
    return ((double)value);
}

bool tcs_set_shift_settings_set_up_delay_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t tcs_set_shift_settings_set_down_delay_encode(double value)
{
    return (uint16_t)(value);
}

double tcs_set_shift_settings_set_down_delay_decode(uint16_t value)
{
    return ((double)value);
}

bool tcs_set_shift_settings_set_down_delay_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t tcs_set_shift_settings_set_output_encode(double value)
{
    return (uint16_t)(value);
}

double tcs_set_shift_settings_set_output_decode(uint16_t value)
{
    return ((double)value);
}

bool tcs_set_shift_settings_set_output_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t tcs_set_shift_settings_set_timeout_encode(double value)
{
    return (uint16_t)(value);
}

double tcs_set_shift_settings_set_timeout_decode(uint16_t value)
{
    return ((double)value);
}

bool tcs_set_shift_settings_set_timeout_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int tcs_clutch_settings_pack(
    uint8_t *dst_p,
    const struct tcs_clutch_settings_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->start, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->start, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->end, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->end, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->friction, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->friction, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->auto_launch, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->auto_launch, 0u, 0xffu);

    return (8);
}

int tcs_clutch_settings_unpack(
    struct tcs_clutch_settings_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->start = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->start |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->end = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->end |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->friction = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->friction |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->auto_launch = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->auto_launch |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int tcs_clutch_settings_init(struct tcs_clutch_settings_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct tcs_clutch_settings_t));

    return 0;
}

uint16_t tcs_clutch_settings_start_encode(double value)
{
    return (uint16_t)(value);
}

double tcs_clutch_settings_start_decode(uint16_t value)
{
    return ((double)value);
}

bool tcs_clutch_settings_start_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t tcs_clutch_settings_end_encode(double value)
{
    return (uint16_t)(value);
}

double tcs_clutch_settings_end_decode(uint16_t value)
{
    return ((double)value);
}

bool tcs_clutch_settings_end_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t tcs_clutch_settings_friction_encode(double value)
{
    return (uint16_t)(value);
}

double tcs_clutch_settings_friction_decode(uint16_t value)
{
    return ((double)value);
}

bool tcs_clutch_settings_friction_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t tcs_clutch_settings_auto_launch_encode(double value)
{
    return (uint16_t)(value);
}

double tcs_clutch_settings_auto_launch_decode(uint16_t value)
{
    return ((double)value);
}

bool tcs_clutch_settings_auto_launch_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int tcs_shift_settings_pack(
    uint8_t *dst_p,
    const struct tcs_shift_settings_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->up_delay, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->up_delay, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->down_delay, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->down_delay, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->output, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->output, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->timeout, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->timeout, 0u, 0xffu);

    return (8);
}

int tcs_shift_settings_unpack(
    struct tcs_shift_settings_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->up_delay = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->up_delay |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->down_delay = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->down_delay |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->output = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->output |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->timeout = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->timeout |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int tcs_shift_settings_init(struct tcs_shift_settings_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct tcs_shift_settings_t));

    return 0;
}

uint16_t tcs_shift_settings_up_delay_encode(double value)
{
    return (uint16_t)(value);
}

double tcs_shift_settings_up_delay_decode(uint16_t value)
{
    return ((double)value);
}

bool tcs_shift_settings_up_delay_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t tcs_shift_settings_down_delay_encode(double value)
{
    return (uint16_t)(value);
}

double tcs_shift_settings_down_delay_decode(uint16_t value)
{
    return ((double)value);
}

bool tcs_shift_settings_down_delay_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t tcs_shift_settings_output_encode(double value)
{
    return (uint16_t)(value);
}

double tcs_shift_settings_output_decode(uint16_t value)
{
    return ((double)value);
}

bool tcs_shift_settings_output_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t tcs_shift_settings_timeout_encode(double value)
{
    return (uint16_t)(value);
}

double tcs_shift_settings_timeout_decode(uint16_t value)
{
    return ((double)value);
}

bool tcs_shift_settings_timeout_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}
